language: python
python:
  - "3.6"
  - "3.5"
cache:
  apt: true
  timeout: 1000
  directories:
    - $HOME/cache
before_cache:
  - find ${HOME}/conda/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
install:
  - sudo apt-get update
  - mkdir -p ${HOME}/cache/pkgs
  - "[ ! -f ${HOME}/cache/miniconda.sh ] && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/cache/miniconda.sh || :"
  - bash ${HOME}/cache/miniconda.sh -b -p ${HOME}/conda && export PATH=${HOME}/conda/bin:$PATH
  - rm -rf ${HOME}/conda/pkgs && ln -s ${HOME}/cache/pkgs ${HOME}/conda/pkgs

  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda env create -q -n skorch-env -f environment.yml python=${TRAVIS_PYTHON_VERSION}
  - source activate skorch-env
  - conda install --file=requirements-dev.txt
  - python setup.py install
  - conda install -c pytorch 'pytorch-cpu>=0.4.1'
script:
  - pytest
